//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 11:50:59 AM KST 
//


package com.wadiz.client.kds.msg.res;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}NMI_RES_HEADER">
 *       &lt;sequence>
 *         &lt;element name="RQ_ACOPNO">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="6"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RQ_ACOPSEQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REQ_SEQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="10"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REPL_SEQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="10"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REPL_DT">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="8"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LMT_REQ_RESULT_CD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TOT_INVST_LMT_AMT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;whiteSpace value="collapse"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ISSUR_INVST_LMT_AMT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;whiteSpace value="collapse"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INVSTR_REALNMNO_TPCD" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *               &lt;whiteSpace value="collapse"/>
 *               &lt;enumeration value="11"/>
 *               &lt;enumeration value="12"/>
 *               &lt;enumeration value="21"/>
 *               &lt;enumeration value="22"/>
 *               &lt;enumeration value="23"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INVSTR_SORT_TPCD" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *               &lt;whiteSpace value="collapse"/>
 *               &lt;enumeration value="01"/>
 *               &lt;enumeration value="02"/>
 *               &lt;enumeration value="03"/>
 *               &lt;enumeration value="04"/>
 *               &lt;enumeration value="05"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VERSION">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rqacopno",
    "rqacopseq",
    "reqseq",
    "replseq",
    "repldt",
    "lmtreqresultcd",
    "totinvstlmtamt",
    "issurinvstlmtamt",
    "invstrrealnmnotpcd",
    "invstrsorttpcd",
    "version"
})
@XmlRootElement(name = "CRWDFSW01RS0001M00")
public class CRWDFSW01RS0001M00
    extends NMIRESHEADER
{

    @XmlElement(name = "RQ_ACOPNO", required = true)
    protected BigInteger rqacopno;
    @XmlElement(name = "RQ_ACOPSEQ", required = true)
    protected String rqacopseq;
    @XmlElement(name = "REQ_SEQ", required = true)
    protected BigInteger reqseq;
    @XmlElement(name = "REPL_SEQ", required = true)
    protected BigInteger replseq;
    @XmlElement(name = "REPL_DT", required = true)
    protected BigInteger repldt;
    @XmlElement(name = "LMT_REQ_RESULT_CD", required = true)
    protected String lmtreqresultcd;
    @XmlElement(name = "TOT_INVST_LMT_AMT")
    protected BigDecimal totinvstlmtamt;
    @XmlElement(name = "ISSUR_INVST_LMT_AMT")
    protected BigDecimal issurinvstlmtamt;
    @XmlElement(name = "INVSTR_REALNMNO_TPCD")
    protected String invstrrealnmnotpcd;
    @XmlElement(name = "INVSTR_SORT_TPCD")
    protected String invstrsorttpcd;
    @XmlElement(name = "VERSION", required = true)
    protected String version;

    /**
     * Gets the value of the rqacopno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRQACOPNO() {
        return rqacopno;
    }

    /**
     * Sets the value of the rqacopno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRQACOPNO(BigInteger value) {
        this.rqacopno = value;
    }

    /**
     * Gets the value of the rqacopseq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRQACOPSEQ() {
        return rqacopseq;
    }

    /**
     * Sets the value of the rqacopseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRQACOPSEQ(String value) {
        this.rqacopseq = value;
    }

    /**
     * Gets the value of the reqseq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getREQSEQ() {
        return reqseq;
    }

    /**
     * Sets the value of the reqseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setREQSEQ(BigInteger value) {
        this.reqseq = value;
    }

    /**
     * Gets the value of the replseq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getREPLSEQ() {
        return replseq;
    }

    /**
     * Sets the value of the replseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setREPLSEQ(BigInteger value) {
        this.replseq = value;
    }

    /**
     * Gets the value of the repldt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getREPLDT() {
        return repldt;
    }

    /**
     * Sets the value of the repldt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setREPLDT(BigInteger value) {
        this.repldt = value;
    }

    /**
     * Gets the value of the lmtreqresultcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLMTREQRESULTCD() {
        return lmtreqresultcd;
    }

    /**
     * Sets the value of the lmtreqresultcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLMTREQRESULTCD(String value) {
        this.lmtreqresultcd = value;
    }

    /**
     * Gets the value of the totinvstlmtamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTOTINVSTLMTAMT() {
        return totinvstlmtamt;
    }

    /**
     * Sets the value of the totinvstlmtamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTOTINVSTLMTAMT(BigDecimal value) {
        this.totinvstlmtamt = value;
    }

    /**
     * Gets the value of the issurinvstlmtamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getISSURINVSTLMTAMT() {
        return issurinvstlmtamt;
    }

    /**
     * Sets the value of the issurinvstlmtamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setISSURINVSTLMTAMT(BigDecimal value) {
        this.issurinvstlmtamt = value;
    }

    /**
     * Gets the value of the invstrrealnmnotpcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVSTRREALNMNOTPCD() {
        return invstrrealnmnotpcd;
    }

    /**
     * Sets the value of the invstrrealnmnotpcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVSTRREALNMNOTPCD(String value) {
        this.invstrrealnmnotpcd = value;
    }

    /**
     * Gets the value of the invstrsorttpcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVSTRSORTTPCD() {
        return invstrsorttpcd;
    }

    /**
     * Sets the value of the invstrsorttpcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVSTRSORTTPCD(String value) {
        this.invstrsorttpcd = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERSION(String value) {
        this.version = value;
    }

}
