//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.11 at 09:07:56 AM KST 
//


package com.wadiz.client.kds.msg.res;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * CRWDFSW01RS0002M00 크라우드펀딩 청약 신청결과
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}NMI_RES_HEADER">
 *       &lt;sequence>
 *         &lt;element name="RQ_ACOPNO">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="6"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RQ_ACOPSEQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REQ_SEQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="10"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REPL_SEQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="10"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REPL_DT">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="8"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ASK_RESULT_CD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rqacopno",
    "rqacopseq",
    "reqseq",
    "replseq",
    "repldt",
    "askresultcd",
    "version"
})
@XmlRootElement(name = "CRWDFSW01RS0002M00")
public class CRWDFSW01RS0002M00
    extends NMIRESHEADER
{

	/**
	 * 요청계좌개설자번호(RQ_ACOPNO)
	 */
    @XmlElement(name = "RQ_ACOPNO", required = true)
    protected BigInteger rqacopno;
    
    /**
     * 요청계좌개설일련번호(RQ_ACOPSEQ)
     */
    @XmlElement(name = "RQ_ACOPSEQ", required = true)
    protected String rqacopseq;
    
    /**
     * 요청일련번호(REQ_SEQ)
     */
    @XmlElement(name = "REQ_SEQ", required = true)
    protected BigInteger reqseq;
    
    /**
     * 응답일련번호(REPL_SEQ)
     */
    @XmlElement(name = "REPL_SEQ", required = true)
    protected BigInteger replseq;
    
    /**
     * 응답일자(REPL_DT)
     */
    @XmlElement(name = "REPL_DT", required = true)
    protected BigInteger repldt;
    
    /**
     * 신청결과코드(ASK_RESULT_CD)
     */
    @XmlElement(name = "ASK_RESULT_CD", required = true)
    protected String askresultcd;
    
    /**
     * 버젼(VERSION)
     */
    @XmlElement(name = "VERSION", required = true)
    protected String version;

    /**
     * Gets the value of the rqacopno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRQACOPNO() {
        return rqacopno;
    }

    /**
     * Sets the value of the rqacopno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRQACOPNO(BigInteger value) {
        this.rqacopno = value;
    }

    /**
     * Gets the value of the rqacopseq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRQACOPSEQ() {
        return rqacopseq;
    }

    /**
     * Sets the value of the rqacopseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRQACOPSEQ(String value) {
        this.rqacopseq = value;
    }

    /**
     * Gets the value of the reqseq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getREQSEQ() {
        return reqseq;
    }

    /**
     * Sets the value of the reqseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setREQSEQ(BigInteger value) {
        this.reqseq = value;
    }

    /**
     * Gets the value of the replseq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getREPLSEQ() {
        return replseq;
    }

    /**
     * Sets the value of the replseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setREPLSEQ(BigInteger value) {
        this.replseq = value;
    }

    /**
     * Gets the value of the repldt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getREPLDT() {
        return repldt;
    }

    /**
     * Sets the value of the repldt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setREPLDT(BigInteger value) {
        this.repldt = value;
    }

    /**
     * Gets the value of the askresultcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getASKRESULTCD() {
        return askresultcd;
    }

    /**
     * Sets the value of the askresultcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setASKRESULTCD(String value) {
        this.askresultcd = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERSION(String value) {
        this.version = value;
    }

}
