//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.11 at 09:08:03 AM KST 
//


package com.wadiz.client.kds.msg.res;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * CRWDFSW01RS0003S00 - 크라우드펀딩 계좌유효성 결과(세부메세지)
 * <p>Java class for CRWDFSW01RS0003S00 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CRWDFSW01RS0003S00">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SUBS_ASK_PROC_SEQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="10"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SECUCO_ACOPNO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="6"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SECUCO_ACOPSEQ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SECUCO_ACOACD" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *               &lt;enumeration value="01"/>
 *               &lt;enumeration value="02"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INVSTR_TRSAC_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AC_CFM_RESULT_CD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;whiteSpace value="collapse"/>
 *               &lt;enumeration value="0000"/>
 *               &lt;enumeration value="0100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CRWDFSW01RS0003S00", propOrder = {
    "subsaskprocseq",
    "secucoacopno",
    "secucoacopseq",
    "secucoacoacd",
    "invstrtrsacno",
    "accfmresultcd"
})
public class CRWDFSW01RS0003S00 {

	/**
	 * 청약신청처리일련번호()
	 */
    @XmlElement(name = "SUBS_ASK_PROC_SEQ", required = true)
    protected BigInteger subsaskprocseq;
    
    /**
     * 위탁사번호(SECUCO_ACOPNO)
     */
    @XmlElement(name = "SECUCO_ACOPNO")
    protected BigInteger secucoacopno;
    
    /**
     * 위탁사계좌일련번호(SECUCO_ACOPSEQ)
     */
    @XmlElement(name = "SECUCO_ACOPSEQ")
    protected String secucoacopseq;
    
    /**
     * 위탁사계좌분류코드(SECUCO_ACOACD)
     */
    @XmlElement(name = "SECUCO_ACOACD")
    protected String secucoacoacd;
    
    /**
     * 위탁계좌번호(INVSTR_TRSAC_NO)
     */
    @XmlElement(name = "INVSTR_TRSAC_NO")
    protected String invstrtrsacno;
    
    /**
     * 계좌유효성결과코드(AC_CFM_RESULT_CD)
     */
    @XmlElement(name = "AC_CFM_RESULT_CD", required = true)
    protected String accfmresultcd;

    /**
     * Gets the value of the subsaskprocseq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSUBSASKPROCSEQ() {
        return subsaskprocseq;
    }

    /**
     * Sets the value of the subsaskprocseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSUBSASKPROCSEQ(BigInteger value) {
        this.subsaskprocseq = value;
    }

    /**
     * Gets the value of the secucoacopno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSECUCOACOPNO() {
        return secucoacopno;
    }

    /**
     * Sets the value of the secucoacopno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSECUCOACOPNO(BigInteger value) {
        this.secucoacopno = value;
    }

    /**
     * Gets the value of the secucoacopseq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECUCOACOPSEQ() {
        return secucoacopseq;
    }

    /**
     * Sets the value of the secucoacopseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECUCOACOPSEQ(String value) {
        this.secucoacopseq = value;
    }

    /**
     * Gets the value of the secucoacoacd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECUCOACOACD() {
        return secucoacoacd;
    }

    /**
     * Sets the value of the secucoacoacd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECUCOACOACD(String value) {
        this.secucoacoacd = value;
    }

    /**
     * Gets the value of the invstrtrsacno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVSTRTRSACNO() {
        return invstrtrsacno;
    }

    /**
     * Sets the value of the invstrtrsacno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVSTRTRSACNO(String value) {
        this.invstrtrsacno = value;
    }

    /**
     * Gets the value of the accfmresultcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCFMRESULTCD() {
        return accfmresultcd;
    }

    /**
     * Sets the value of the accfmresultcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCFMRESULTCD(String value) {
        this.accfmresultcd = value;
    }

}
