//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.11 at 09:06:40 AM KST 
//


package com.wadiz.client.kds.msg.res;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 응답전문
 * <p>Java class for NMI_RES_HEADER complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NMI_RES_HEADER">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NMI_REQ_UUID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="36"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NMI_RES_UUID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="36"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SEND_DATE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PROCESS_CD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BIZ_EXCEPTION_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BIZ_EXCEPTION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VALID_EXCEPTION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TASK_EXCEPTION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NMI_RES_HEADER", propOrder = {
    "nmirequuid",
    "nmiresuuid",
    "senddate",
    "processcd",
    "bizexceptioncode",
    "bizexception",
    "validexception",
    "taskexception"
})
public class NMIRESHEADER {

	/**
	 * 요청전문식별번호(NMI_REQ_UUID)
	 */
    @XmlElement(name = "NMI_REQ_UUID", required = true)
    protected String nmirequuid;
    
    /**
	 * 응답전문식별번호(NMI_RES_UUID)
	 */
    @XmlElement(name = "NMI_RES_UUID", required = true)
    protected String nmiresuuid;
    
    /**
	 * 전문발송일시(SEND_DATE)
	 */
    @XmlElement(name = "SEND_DATE", required = true)
    protected String senddate;
    
    /**
	 * 처리결과코드(PROCESS_CD)
	 * |순번|코드번호|내용                                |비고
	 *  1  N000   정상처리
	 *	2  N100   정합성검증오류 상세내용은    VALID_EXCEPTION SET
	 *	3  N200   스키마정보 없음
	 *	4  N300   미등록 IP 오류
	 *	5  N400   업무로직 처리중 오류
	 *	6  N500   업무정지된 참가기관
	 *	7  N600   미등록 사용자
	 *	8  N700   미등록 전문오류
	 *	9  N800   미인가된 접근
	 */
    @XmlElement(name = "PROCESS_CD", required = true)
    protected String processcd;
    
    /**
	 * 업무오류코드(BIZ_EXCEPTION_CODE): 미사용
	 */
    @XmlElement(name = "BIZ_EXCEPTION_CODE")
    protected String bizexceptioncode;
    
    /**
	 * 업무오류메시지(BIZ_EXCEPTION): 미사용
	 */
    @XmlElement(name = "BIZ_EXCEPTION")
    protected String bizexception;
    
    /**
	 * 정합성검증메시지(VALID_EXCEPTION)
	 */
    @XmlElement(name = "VALID_EXCEPTION")
    protected String validexception;
    
    /**
	 * (TASK_EXCEPTION)
	 */
    @XmlElement(name = "TASK_EXCEPTION")
    protected String taskexception;

    /**
     * Gets the value of the nmirequuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNMIREQUUID() {
        return nmirequuid;
    }

    /**
     * Sets the value of the nmirequuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNMIREQUUID(String value) {
        this.nmirequuid = value;
    }

    /**
     * Gets the value of the nmiresuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNMIRESUUID() {
        return nmiresuuid;
    }

    /**
     * Sets the value of the nmiresuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNMIRESUUID(String value) {
        this.nmiresuuid = value;
    }

    /**
     * Gets the value of the senddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSENDDATE() {
        return senddate;
    }

    /**
     * Sets the value of the senddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSENDDATE(String value) {
        this.senddate = value;
    }

    /**
     * Gets the value of the processcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROCESSCD() {
        return processcd;
    }

    /**
     * Sets the value of the processcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROCESSCD(String value) {
        this.processcd = value;
    }

    /**
     * Gets the value of the bizexceptioncode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIZEXCEPTIONCODE() {
        return bizexceptioncode;
    }

    /**
     * Sets the value of the bizexceptioncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIZEXCEPTIONCODE(String value) {
        this.bizexceptioncode = value;
    }

    /**
     * Gets the value of the bizexception property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIZEXCEPTION() {
        return bizexception;
    }

    /**
     * Sets the value of the bizexception property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIZEXCEPTION(String value) {
        this.bizexception = value;
    }

    /**
     * Gets the value of the validexception property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALIDEXCEPTION() {
        return validexception;
    }

    /**
     * Sets the value of the validexception property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALIDEXCEPTION(String value) {
        this.validexception = value;
    }

    /**
     * Gets the value of the taskexception property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTASKEXCEPTION() {
        return taskexception;
    }

    /**
     * Sets the value of the taskexception property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTASKEXCEPTION(String value) {
        this.taskexception = value;
    }

}
