package com.wadiz.client.kds.persistence;

import java.util.List;

import com.wadiz.client.kds.model.ClientRequest;
import com.wadiz.client.kds.model.ClientResponse;

public interface ClientResponseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ClientResponse
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	int deleteByPrimaryKey(Long responseSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ClientResponse
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	int insert(ClientResponse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ClientResponse
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	int insertSelective(ClientResponse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ClientResponse
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	ClientResponse selectByPrimaryKey(Long responseSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ClientResponse
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	int updateByPrimaryKeySelective(ClientResponse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ClientResponse
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	int updateByPrimaryKey(ClientResponse record);

	List<ClientRequest> selectByReqlSeq(String subsaskprocseq);
	
	ClientResponse selectInvestedResponse(String investId);
}