package com.wadiz.client.kds.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wadiz.client.kds.model.ClientRequest;
import com.wadiz.client.kds.model.ClientRequestExample;

public interface ClientRequestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ClientRequest
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	int deleteByPrimaryKey(Integer requestSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ClientRequest
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	int insert(ClientRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ClientRequest
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	int insertSelective(ClientRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ClientRequest
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	ClientRequest selectByPrimaryKey(Integer requestSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ClientRequest
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	int updateByPrimaryKeySelective(ClientRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ClientRequest
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	int updateByPrimaryKey(ClientRequest record);
}