package com.wadiz.client.kds.persistence;

import com.wadiz.client.kds.model.TbBusinessLicenseInfo;

public interface TbBusinessLicenseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbBusinessLicenseInfo
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    int deleteByPrimaryKey(Integer businessLicenseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbBusinessLicenseInfo
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    int insert(TbBusinessLicenseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbBusinessLicenseInfo
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    int insertSelective(TbBusinessLicenseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbBusinessLicenseInfo
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    TbBusinessLicenseInfo selectByPrimaryKey(Integer businessLicenseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbBusinessLicenseInfo
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    int updateByPrimaryKeySelective(TbBusinessLicenseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbBusinessLicenseInfo
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    int updateByPrimaryKey(TbBusinessLicenseInfo record);

    TbBusinessLicenseInfo selectByCorpRegNum(String corpRegNum);

    TbBusinessLicenseInfo selectBusinessLicenseInfoByCorpRegNo(String corpRegNo);
}