package com.wadiz.client.kds.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wadiz.client.kds.model.TbPersonalUserInfo;

public interface TbPersonalUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbPersonalUserInfo
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbPersonalUserInfo
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int insert(TbPersonalUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbPersonalUserInfo
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int insertSelective(TbPersonalUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbPersonalUserInfo
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    TbPersonalUserInfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbPersonalUserInfo
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int updateByPrimaryKeySelective(TbPersonalUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbPersonalUserInfo
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int updateByPrimaryKey(TbPersonalUserInfo record);

    TbPersonalUserInfo selectByScrtAccountNo(String invstrtrsacno);

    TbPersonalUserInfo selectPersonalUserInfoBySsn(@Param("encSsn1") String encSsn1,@Param("encSsn2") String encSsn2);
    
    List<String> selectInvalidAccountInvestList(String accountNo);
}