package com.wadiz.client.kds.persistence;

import com.wadiz.client.kds.model.TbUserAccntAuth;
import com.wadiz.client.kds.model.TbUserAccntAuthKey;

public interface TbUserAccntAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbUserAccntAuth
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int deleteByPrimaryKey(TbUserAccntAuthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbUserAccntAuth
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int insert(TbUserAccntAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbUserAccntAuth
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int insertSelective(TbUserAccntAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbUserAccntAuth
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    TbUserAccntAuth selectByPrimaryKey(TbUserAccntAuthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbUserAccntAuth
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int updateByPrimaryKeySelective(TbUserAccntAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbUserAccntAuth
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int updateByPrimaryKey(TbUserAccntAuth record);
}