package com.wadiz.client.kds.persistence;

import com.wadiz.client.kds.model.TbUserAccntAuthHis;

public interface TbUserAccntAuthHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbUserAccntAuthHis
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int deleteByPrimaryKey(Integer hisNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbUserAccntAuthHis
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int insert(TbUserAccntAuthHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbUserAccntAuthHis
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int insertSelective(TbUserAccntAuthHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbUserAccntAuthHis
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    TbUserAccntAuthHis selectByPrimaryKey(Integer hisNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbUserAccntAuthHis
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int updateByPrimaryKeySelective(TbUserAccntAuthHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbUserAccntAuthHis
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    int updateByPrimaryKey(TbUserAccntAuthHis record);
}