//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 11:49:11 AM KST 
//


package com.wadiz.client.kds.msg.req;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}NMI_REQ_HEADER">
 *       &lt;sequence>
 *         &lt;element name="RQ_ACOPNO">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="6"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RQ_ACOPSEQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REQ_SEQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="10"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REQ_TPCD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *               &lt;whiteSpace value="collapse"/>
 *               &lt;enumeration value="01"/>
 *               &lt;enumeration value="02"/>
 *               &lt;enumeration value="09"/>
 *               &lt;enumeration value="91"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ISSUR_BUZNO">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SECN_TPCD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *               &lt;enumeration value="11"/>
 *               &lt;enumeration value="21"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ISIN">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SUBS_BEGIN_DT">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SUBS_EXPRY_DT">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INVSTR_REALNMNO">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INVSTR_REALNMNO_TPCD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *               &lt;enumeration value="11"/>
 *               &lt;enumeration value="12"/>
 *               &lt;enumeration value="21"/>
 *               &lt;enumeration value="22"/>
 *               &lt;enumeration value="23"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INVSTR_BUZNO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INVSTR_SORT_CD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *               &lt;enumeration value="01"/>
 *               &lt;enumeration value="02"/>
 *               &lt;enumeration value="03"/>
 *               &lt;enumeration value="04"/>
 *               &lt;enumeration value="05"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INVSTR_NM">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SUBS_AMT">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SUBS_QTY">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SECUCO_ACOPNO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SECUCO_ACOPSEQ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SECUCO_ACOACD" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *               &lt;enumeration value="01"/>
 *               &lt;enumeration value="02"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INVSTR_TRSAC_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rqacopno",
    "rqacopseq",
    "reqseq",
    "reqtpcd",
    "issurbuzno",
    "secntpcd",
    "isin",
    "subsbegindt",
    "subsexprydt",
    "invstrrealnmno",
    "invstrrealnmnotpcd",
    "invstrbuzno",
    "invstrsortcd",
    "invstrnm",
    "subsamt",
    "subsqty",
    "secucoacopno",
    "secucoacopseq",
    "secucoacoacd",
    "invstrtrsacno",
    "version"
})
@XmlRootElement(name = "CRWDFSW01RQ0002M00")
public class CRWDFSW01RQ0002M00
    extends NMIREQHEADER
{

    @XmlElement(name = "RQ_ACOPNO", required = true)
    protected BigInteger rqacopno;
    @XmlElement(name = "RQ_ACOPSEQ", required = true)
    protected String rqacopseq;
    @XmlElement(name = "REQ_SEQ", required = true)
    protected BigInteger reqseq;
    @XmlElement(name = "REQ_TPCD", required = true)
    protected String reqtpcd;
    @XmlElement(name = "ISSUR_BUZNO", required = true)
    protected String issurbuzno;
    @XmlElement(name = "SECN_TPCD", required = true)
    protected String secntpcd;
    @XmlElement(name = "ISIN", required = true)
    protected String isin;
    @XmlElement(name = "SUBS_BEGIN_DT", required = true)
    protected BigInteger subsbegindt;
    @XmlElement(name = "SUBS_EXPRY_DT", required = true)
    protected BigInteger subsexprydt;
    @XmlElement(name = "INVSTR_REALNMNO", required = true)
    protected String invstrrealnmno;
    @XmlElement(name = "INVSTR_REALNMNO_TPCD", required = true)
    protected String invstrrealnmnotpcd;
    @XmlElement(name = "INVSTR_BUZNO")
    protected String invstrbuzno;
    @XmlElement(name = "INVSTR_SORT_CD", required = true)
    protected String invstrsortcd;
    @XmlElement(name = "INVSTR_NM", required = true)
    protected String invstrnm;
    @XmlElement(name = "SUBS_AMT", required = true)
    protected BigDecimal subsamt;
    @XmlElement(name = "SUBS_QTY", required = true)
    protected BigDecimal subsqty;
    @XmlElement(name = "SECUCO_ACOPNO")
    protected BigInteger secucoacopno;
    @XmlElement(name = "SECUCO_ACOPSEQ")
    protected String secucoacopseq;
    @XmlElement(name = "SECUCO_ACOACD")
    protected String secucoacoacd;
    @XmlElement(name = "INVSTR_TRSAC_NO")
    protected String invstrtrsacno;
    @XmlElement(name = "VERSION", required = true)
    protected String version;

    /**
     * Gets the value of the rqacopno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRQACOPNO() {
        return rqacopno;
    }

    /**
     * Sets the value of the rqacopno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRQACOPNO(BigInteger value) {
        this.rqacopno = value;
    }

    /**
     * Gets the value of the rqacopseq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRQACOPSEQ() {
        return rqacopseq;
    }

    /**
     * Sets the value of the rqacopseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRQACOPSEQ(String value) {
        this.rqacopseq = value;
    }

    /**
     * Gets the value of the reqseq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getREQSEQ() {
        return reqseq;
    }

    /**
     * Sets the value of the reqseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setREQSEQ(BigInteger value) {
        this.reqseq = value;
    }

    /**
     * Gets the value of the reqtpcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREQTPCD() {
        return reqtpcd;
    }

    /**
     * Sets the value of the reqtpcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREQTPCD(String value) {
        this.reqtpcd = value;
    }

    /**
     * Gets the value of the issurbuzno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSURBUZNO() {
        return issurbuzno;
    }

    /**
     * Sets the value of the issurbuzno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSURBUZNO(String value) {
        this.issurbuzno = value;
    }

    /**
     * Gets the value of the secntpcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECNTPCD() {
        return secntpcd;
    }

    /**
     * Sets the value of the secntpcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECNTPCD(String value) {
        this.secntpcd = value;
    }

    /**
     * Gets the value of the isin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISIN() {
        return isin;
    }

    /**
     * Sets the value of the isin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISIN(String value) {
        this.isin = value;
    }

    /**
     * Gets the value of the subsbegindt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSUBSBEGINDT() {
        return subsbegindt;
    }

    /**
     * Sets the value of the subsbegindt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSUBSBEGINDT(BigInteger value) {
        this.subsbegindt = value;
    }

    /**
     * Gets the value of the subsexprydt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSUBSEXPRYDT() {
        return subsexprydt;
    }

    /**
     * Sets the value of the subsexprydt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSUBSEXPRYDT(BigInteger value) {
        this.subsexprydt = value;
    }

    /**
     * Gets the value of the invstrrealnmno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVSTRREALNMNO() {
        return invstrrealnmno;
    }

    /**
     * Sets the value of the invstrrealnmno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVSTRREALNMNO(String value) {
        this.invstrrealnmno = value;
    }

    /**
     * Gets the value of the invstrrealnmnotpcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVSTRREALNMNOTPCD() {
        return invstrrealnmnotpcd;
    }

    /**
     * Sets the value of the invstrrealnmnotpcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVSTRREALNMNOTPCD(String value) {
        this.invstrrealnmnotpcd = value;
    }

    /**
     * Gets the value of the invstrbuzno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVSTRBUZNO() {
        return invstrbuzno;
    }

    /**
     * Sets the value of the invstrbuzno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVSTRBUZNO(String value) {
        this.invstrbuzno = value;
    }

    /**
     * Gets the value of the invstrsortcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVSTRSORTCD() {
        return invstrsortcd;
    }

    /**
     * Sets the value of the invstrsortcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVSTRSORTCD(String value) {
        this.invstrsortcd = value;
    }

    /**
     * Gets the value of the invstrnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVSTRNM() {
        return invstrnm;
    }

    /**
     * Sets the value of the invstrnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVSTRNM(String value) {
        this.invstrnm = value;
    }

    /**
     * Gets the value of the subsamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSUBSAMT() {
        return subsamt;
    }

    /**
     * Sets the value of the subsamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSUBSAMT(BigDecimal value) {
        this.subsamt = value;
    }

    /**
     * Gets the value of the subsqty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSUBSQTY() {
        return subsqty;
    }

    /**
     * Sets the value of the subsqty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSUBSQTY(BigDecimal value) {
        this.subsqty = value;
    }

    /**
     * Gets the value of the secucoacopno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSECUCOACOPNO() {
        return secucoacopno;
    }

    /**
     * Sets the value of the secucoacopno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSECUCOACOPNO(BigInteger value) {
        this.secucoacopno = value;
    }

    /**
     * Gets the value of the secucoacopseq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECUCOACOPSEQ() {
        return secucoacopseq;
    }

    /**
     * Sets the value of the secucoacopseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECUCOACOPSEQ(String value) {
        this.secucoacopseq = value;
    }

    /**
     * Gets the value of the secucoacoacd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECUCOACOACD() {
        return secucoacoacd;
    }

    /**
     * Sets the value of the secucoacoacd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECUCOACOACD(String value) {
        this.secucoacoacd = value;
    }

    /**
     * Gets the value of the invstrtrsacno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVSTRTRSACNO() {
        return invstrtrsacno;
    }

    /**
     * Sets the value of the invstrtrsacno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVSTRTRSACNO(String value) {
        this.invstrtrsacno = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERSION(String value) {
        this.version = value;
    }

}
