package com.wadiz.client.kds.model;

import java.util.Date;

public class ClientRequest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ClientRequest.request_seq
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	private Integer requestSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ClientRequest.request_uuid
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	private String requestUuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ClientRequest.type
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ClientRequest.ref_id
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	private Integer refId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ClientRequest.content
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ClientRequest.reg_time
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	private Date regTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ClientRequest.request_seq
	 * @return  the value of ClientRequest.request_seq
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	public Integer getRequestSeq() {
		return requestSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ClientRequest.request_seq
	 * @param requestSeq  the value for ClientRequest.request_seq
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	public void setRequestSeq(Integer requestSeq) {
		this.requestSeq = requestSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ClientRequest.request_uuid
	 * @return  the value of ClientRequest.request_uuid
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	public String getRequestUuid() {
		return requestUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ClientRequest.request_uuid
	 * @param requestUuid  the value for ClientRequest.request_uuid
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	public void setRequestUuid(String requestUuid) {
		this.requestUuid = requestUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ClientRequest.type
	 * @return  the value of ClientRequest.type
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ClientRequest.type
	 * @param type  the value for ClientRequest.type
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ClientRequest.ref_id
	 * @return  the value of ClientRequest.ref_id
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	public Integer getRefId() {
		return refId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ClientRequest.ref_id
	 * @param refId  the value for ClientRequest.ref_id
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	public void setRefId(Integer refId) {
		this.refId = refId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ClientRequest.content
	 * @return  the value of ClientRequest.content
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ClientRequest.content
	 * @param content  the value for ClientRequest.content
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ClientRequest.reg_time
	 * @return  the value of ClientRequest.reg_time
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ClientRequest.reg_time
	 * @param regTime  the value for ClientRequest.reg_time
	 * @mbggenerated  Tue Jan 26 10:45:23 KST 2016
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}
}