package com.wadiz.client.kds.model;

import java.util.Date;

public class ClientResponse {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ClientResponse.response_seq
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	private Long responseSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ClientResponse.response_uuid
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	private String responseUuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ClientResponse.request_uuid
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	private String requestUuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ClientResponse.content
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ClientResponse.reg_time
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	private Date regTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ClientResponse.repl_seq
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	private Long replSeq;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ClientResponse.response_seq
	 * @return  the value of ClientResponse.response_seq
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	public Long getResponseSeq() {
		return responseSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ClientResponse.response_seq
	 * @param responseSeq  the value for ClientResponse.response_seq
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	public void setResponseSeq(Long responseSeq) {
		this.responseSeq = responseSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ClientResponse.response_uuid
	 * @return  the value of ClientResponse.response_uuid
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	public String getResponseUuid() {
		return responseUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ClientResponse.response_uuid
	 * @param responseUuid  the value for ClientResponse.response_uuid
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	public void setResponseUuid(String responseUuid) {
		this.responseUuid = responseUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ClientResponse.request_uuid
	 * @return  the value of ClientResponse.request_uuid
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	public String getRequestUuid() {
		return requestUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ClientResponse.request_uuid
	 * @param requestUuid  the value for ClientResponse.request_uuid
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	public void setRequestUuid(String requestUuid) {
		this.requestUuid = requestUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ClientResponse.content
	 * @return  the value of ClientResponse.content
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ClientResponse.content
	 * @param content  the value for ClientResponse.content
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ClientResponse.reg_time
	 * @return  the value of ClientResponse.reg_time
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ClientResponse.reg_time
	 * @param regTime  the value for ClientResponse.reg_time
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ClientResponse.repl_seq
	 * @return  the value of ClientResponse.repl_seq
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	public Long getReplSeq() {
		return replSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ClientResponse.repl_seq
	 * @param replSeq  the value for ClientResponse.repl_seq
	 * @mbggenerated  Mon Jan 25 00:06:11 KST 2016
	 */
	public void setReplSeq(Long replSeq) {
		this.replSeq = replSeq;
	}
}