package com.wadiz.client.kds.model;

import java.util.Date;

public class TbBusinessLicenseInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.BusinessLicenseId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private Integer businessLicenseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.CorpType
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String corptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.BusinessRegNumber
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String businessRegNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.CorpName
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String corpname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.RepresentName
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String representname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.BusinessOpenDate
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String businessopendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.BsnsType
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String bsnstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.CorpRegNum
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String corpRegNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.BusinessLicensePhotoId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private Integer businesslicensephotoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.HeadOfficePostCode
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String headofficepostcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.HeadOfficeLocation1
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String headofficelocation1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.HeadOfficeLocation2
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String headofficelocation2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.Workforce
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String workforce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.Email
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.HomePageOrBlog
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String homepageorblog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.FacebookUri
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String facebookuri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.TwitterUrl
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String twitterurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.LogoPhotoId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private Integer logophotoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.AtcIncorpPhotoId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private Integer atcincorpphotoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.CertifiedPhotoId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private Integer certifiedphotoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.RegUserId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private Integer regUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.RegDate
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private Date regdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.UpdateUserId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private Integer updateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.UpdateDate
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.CorpManagerName
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String corpmanagername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.CorpManagerEmail
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String corpmanageremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.CorpManagerPhoneNumber
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String corpmanagerphonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.PhoneNumber
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.ScrtCpCode
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String scrtcpcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbBusinessLicenseInfo.ScrtAccountNo
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    private String scrtaccountno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.BusinessLicenseId
     *
     * @return the value of TbBusinessLicenseInfo.BusinessLicenseId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public Integer getBusinessLicenseId() {
        return businessLicenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.BusinessLicenseId
     *
     * @param businessLicenseId the value for TbBusinessLicenseInfo.BusinessLicenseId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setBusinessLicenseId(Integer businessLicenseId) {
        this.businessLicenseId = businessLicenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.CorpType
     *
     * @return the value of TbBusinessLicenseInfo.CorpType
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getCorptype() {
        return corptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.CorpType
     *
     * @param corptype the value for TbBusinessLicenseInfo.CorpType
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setCorptype(String corptype) {
        this.corptype = corptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.BusinessRegNumber
     *
     * @return the value of TbBusinessLicenseInfo.BusinessRegNumber
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getBusinessRegNumber() {
        return businessRegNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.BusinessRegNumber
     *
     * @param businessRegNumber the value for TbBusinessLicenseInfo.BusinessRegNumber
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setBusinessRegNumber(String businessRegNumber) {
        this.businessRegNumber = businessRegNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.CorpName
     *
     * @return the value of TbBusinessLicenseInfo.CorpName
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getCorpname() {
        return corpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.CorpName
     *
     * @param corpname the value for TbBusinessLicenseInfo.CorpName
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setCorpname(String corpname) {
        this.corpname = corpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.RepresentName
     *
     * @return the value of TbBusinessLicenseInfo.RepresentName
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getRepresentname() {
        return representname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.RepresentName
     *
     * @param representname the value for TbBusinessLicenseInfo.RepresentName
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setRepresentname(String representname) {
        this.representname = representname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.BusinessOpenDate
     *
     * @return the value of TbBusinessLicenseInfo.BusinessOpenDate
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getBusinessopendate() {
        return businessopendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.BusinessOpenDate
     *
     * @param businessopendate the value for TbBusinessLicenseInfo.BusinessOpenDate
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setBusinessopendate(String businessopendate) {
        this.businessopendate = businessopendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.BsnsType
     *
     * @return the value of TbBusinessLicenseInfo.BsnsType
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getBsnstype() {
        return bsnstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.BsnsType
     *
     * @param bsnstype the value for TbBusinessLicenseInfo.BsnsType
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setBsnstype(String bsnstype) {
        this.bsnstype = bsnstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.CorpRegNum
     *
     * @return the value of TbBusinessLicenseInfo.CorpRegNum
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getCorpRegNum() {
        return corpRegNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.CorpRegNum
     *
     * @param corpRegNum the value for TbBusinessLicenseInfo.CorpRegNum
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setCorpRegNum(String corpRegNum) {
        this.corpRegNum = corpRegNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.BusinessLicensePhotoId
     *
     * @return the value of TbBusinessLicenseInfo.BusinessLicensePhotoId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public Integer getBusinesslicensephotoid() {
        return businesslicensephotoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.BusinessLicensePhotoId
     *
     * @param businesslicensephotoid the value for TbBusinessLicenseInfo.BusinessLicensePhotoId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setBusinesslicensephotoid(Integer businesslicensephotoid) {
        this.businesslicensephotoid = businesslicensephotoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.HeadOfficePostCode
     *
     * @return the value of TbBusinessLicenseInfo.HeadOfficePostCode
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getHeadofficepostcode() {
        return headofficepostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.HeadOfficePostCode
     *
     * @param headofficepostcode the value for TbBusinessLicenseInfo.HeadOfficePostCode
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setHeadofficepostcode(String headofficepostcode) {
        this.headofficepostcode = headofficepostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.HeadOfficeLocation1
     *
     * @return the value of TbBusinessLicenseInfo.HeadOfficeLocation1
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getHeadofficelocation1() {
        return headofficelocation1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.HeadOfficeLocation1
     *
     * @param headofficelocation1 the value for TbBusinessLicenseInfo.HeadOfficeLocation1
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setHeadofficelocation1(String headofficelocation1) {
        this.headofficelocation1 = headofficelocation1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.HeadOfficeLocation2
     *
     * @return the value of TbBusinessLicenseInfo.HeadOfficeLocation2
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getHeadofficelocation2() {
        return headofficelocation2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.HeadOfficeLocation2
     *
     * @param headofficelocation2 the value for TbBusinessLicenseInfo.HeadOfficeLocation2
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setHeadofficelocation2(String headofficelocation2) {
        this.headofficelocation2 = headofficelocation2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.Workforce
     *
     * @return the value of TbBusinessLicenseInfo.Workforce
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getWorkforce() {
        return workforce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.Workforce
     *
     * @param workforce the value for TbBusinessLicenseInfo.Workforce
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setWorkforce(String workforce) {
        this.workforce = workforce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.Email
     *
     * @return the value of TbBusinessLicenseInfo.Email
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.Email
     *
     * @param email the value for TbBusinessLicenseInfo.Email
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.HomePageOrBlog
     *
     * @return the value of TbBusinessLicenseInfo.HomePageOrBlog
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getHomepageorblog() {
        return homepageorblog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.HomePageOrBlog
     *
     * @param homepageorblog the value for TbBusinessLicenseInfo.HomePageOrBlog
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setHomepageorblog(String homepageorblog) {
        this.homepageorblog = homepageorblog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.FacebookUri
     *
     * @return the value of TbBusinessLicenseInfo.FacebookUri
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getFacebookuri() {
        return facebookuri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.FacebookUri
     *
     * @param facebookuri the value for TbBusinessLicenseInfo.FacebookUri
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setFacebookuri(String facebookuri) {
        this.facebookuri = facebookuri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.TwitterUrl
     *
     * @return the value of TbBusinessLicenseInfo.TwitterUrl
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getTwitterurl() {
        return twitterurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.TwitterUrl
     *
     * @param twitterurl the value for TbBusinessLicenseInfo.TwitterUrl
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setTwitterurl(String twitterurl) {
        this.twitterurl = twitterurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.LogoPhotoId
     *
     * @return the value of TbBusinessLicenseInfo.LogoPhotoId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public Integer getLogophotoid() {
        return logophotoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.LogoPhotoId
     *
     * @param logophotoid the value for TbBusinessLicenseInfo.LogoPhotoId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setLogophotoid(Integer logophotoid) {
        this.logophotoid = logophotoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.AtcIncorpPhotoId
     *
     * @return the value of TbBusinessLicenseInfo.AtcIncorpPhotoId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public Integer getAtcincorpphotoid() {
        return atcincorpphotoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.AtcIncorpPhotoId
     *
     * @param atcincorpphotoid the value for TbBusinessLicenseInfo.AtcIncorpPhotoId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setAtcincorpphotoid(Integer atcincorpphotoid) {
        this.atcincorpphotoid = atcincorpphotoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.CertifiedPhotoId
     *
     * @return the value of TbBusinessLicenseInfo.CertifiedPhotoId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public Integer getCertifiedphotoid() {
        return certifiedphotoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.CertifiedPhotoId
     *
     * @param certifiedphotoid the value for TbBusinessLicenseInfo.CertifiedPhotoId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setCertifiedphotoid(Integer certifiedphotoid) {
        this.certifiedphotoid = certifiedphotoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.RegUserId
     *
     * @return the value of TbBusinessLicenseInfo.RegUserId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public Integer getRegUserId() {
        return regUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.RegUserId
     *
     * @param regUserId the value for TbBusinessLicenseInfo.RegUserId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setRegUserId(Integer regUserId) {
        this.regUserId = regUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.RegDate
     *
     * @return the value of TbBusinessLicenseInfo.RegDate
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.RegDate
     *
     * @param regdate the value for TbBusinessLicenseInfo.RegDate
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.UpdateUserId
     *
     * @return the value of TbBusinessLicenseInfo.UpdateUserId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.UpdateUserId
     *
     * @param updateuserid the value for TbBusinessLicenseInfo.UpdateUserId
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.UpdateDate
     *
     * @return the value of TbBusinessLicenseInfo.UpdateDate
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.UpdateDate
     *
     * @param updatedate the value for TbBusinessLicenseInfo.UpdateDate
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.CorpManagerName
     *
     * @return the value of TbBusinessLicenseInfo.CorpManagerName
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getCorpmanagername() {
        return corpmanagername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.CorpManagerName
     *
     * @param corpmanagername the value for TbBusinessLicenseInfo.CorpManagerName
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setCorpmanagername(String corpmanagername) {
        this.corpmanagername = corpmanagername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.CorpManagerEmail
     *
     * @return the value of TbBusinessLicenseInfo.CorpManagerEmail
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getCorpmanageremail() {
        return corpmanageremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.CorpManagerEmail
     *
     * @param corpmanageremail the value for TbBusinessLicenseInfo.CorpManagerEmail
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setCorpmanageremail(String corpmanageremail) {
        this.corpmanageremail = corpmanageremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.CorpManagerPhoneNumber
     *
     * @return the value of TbBusinessLicenseInfo.CorpManagerPhoneNumber
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getCorpmanagerphonenumber() {
        return corpmanagerphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.CorpManagerPhoneNumber
     *
     * @param corpmanagerphonenumber the value for TbBusinessLicenseInfo.CorpManagerPhoneNumber
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setCorpmanagerphonenumber(String corpmanagerphonenumber) {
        this.corpmanagerphonenumber = corpmanagerphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.PhoneNumber
     *
     * @return the value of TbBusinessLicenseInfo.PhoneNumber
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.PhoneNumber
     *
     * @param phonenumber the value for TbBusinessLicenseInfo.PhoneNumber
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.ScrtCpCode
     *
     * @return the value of TbBusinessLicenseInfo.ScrtCpCode
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getScrtcpcode() {
        return scrtcpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.ScrtCpCode
     *
     * @param scrtcpcode the value for TbBusinessLicenseInfo.ScrtCpCode
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setScrtcpcode(String scrtcpcode) {
        this.scrtcpcode = scrtcpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbBusinessLicenseInfo.ScrtAccountNo
     *
     * @return the value of TbBusinessLicenseInfo.ScrtAccountNo
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public String getScrtaccountno() {
        return scrtaccountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbBusinessLicenseInfo.ScrtAccountNo
     *
     * @param scrtaccountno the value for TbBusinessLicenseInfo.ScrtAccountNo
     *
     * @mbggenerated Mon Jan 25 12:15:16 KST 2016
     */
    public void setScrtaccountno(String scrtaccountno) {
        this.scrtaccountno = scrtaccountno;
    }
}