package com.wadiz.client.kds.model;

import java.util.Date;

public class TbInvestKsdAccountCheckHis {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheckHis.HisNo
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private Integer hisNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheckHis.InvestId
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private Integer investId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheckHis.AskProcDt
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private String askProcDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheckHis.KsdReqSeq
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private Integer ksdReqSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheckHis.Stat
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private String stat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheckHis.ResultCode
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private String resultCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheckHis.RegDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private Date regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheckHis.ReqDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private Date reqDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheckHis.ResDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private Date resDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheckHis.HisNo
	 * @return  the value of TbInvestKsdAccountCheckHis.HisNo
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public Integer getHisNo() {
		return hisNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheckHis.HisNo
	 * @param hisNo  the value for TbInvestKsdAccountCheckHis.HisNo
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setHisNo(Integer hisNo) {
		this.hisNo = hisNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheckHis.InvestId
	 * @return  the value of TbInvestKsdAccountCheckHis.InvestId
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public Integer getInvestId() {
		return investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheckHis.InvestId
	 * @param investId  the value for TbInvestKsdAccountCheckHis.InvestId
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setInvestId(Integer investId) {
		this.investId = investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheckHis.AskProcDt
	 * @return  the value of TbInvestKsdAccountCheckHis.AskProcDt
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public String getAskProcDt() {
		return askProcDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheckHis.AskProcDt
	 * @param askProcDt  the value for TbInvestKsdAccountCheckHis.AskProcDt
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setAskProcDt(String askProcDt) {
		this.askProcDt = askProcDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheckHis.KsdReqSeq
	 * @return  the value of TbInvestKsdAccountCheckHis.KsdReqSeq
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public Integer getKsdReqSeq() {
		return ksdReqSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheckHis.KsdReqSeq
	 * @param ksdReqSeq  the value for TbInvestKsdAccountCheckHis.KsdReqSeq
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setKsdReqSeq(Integer ksdReqSeq) {
		this.ksdReqSeq = ksdReqSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheckHis.Stat
	 * @return  the value of TbInvestKsdAccountCheckHis.Stat
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheckHis.Stat
	 * @param stat  the value for TbInvestKsdAccountCheckHis.Stat
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setStat(String stat) {
		this.stat = stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheckHis.ResultCode
	 * @return  the value of TbInvestKsdAccountCheckHis.ResultCode
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public String getResultCode() {
		return resultCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheckHis.ResultCode
	 * @param resultCode  the value for TbInvestKsdAccountCheckHis.ResultCode
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheckHis.RegDate
	 * @return  the value of TbInvestKsdAccountCheckHis.RegDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheckHis.RegDate
	 * @param regDate  the value for TbInvestKsdAccountCheckHis.RegDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheckHis.ReqDate
	 * @return  the value of TbInvestKsdAccountCheckHis.ReqDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public Date getReqDate() {
		return reqDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheckHis.ReqDate
	 * @param reqDate  the value for TbInvestKsdAccountCheckHis.ReqDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setReqDate(Date reqDate) {
		this.reqDate = reqDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheckHis.ResDate
	 * @return  the value of TbInvestKsdAccountCheckHis.ResDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public Date getResDate() {
		return resDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheckHis.ResDate
	 * @param resDate  the value for TbInvestKsdAccountCheckHis.ResDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setResDate(Date resDate) {
		this.resDate = resDate;
	}

	@Override
	public String toString() {
		return "TbInvestKsdAccountCheckHis [hisNo=" + hisNo + ", investId=" + investId + ", askProcDt=" + askProcDt
				+ ", ksdReqSeq=" + ksdReqSeq + ", stat=" + stat + ", resultCode=" + resultCode + ", regDate=" + regDate
				+ ", reqDate=" + reqDate + ", resDate=" + resDate + "]";
	}
}