package com.wadiz.client.kds.model;

import java.util.Date;

public class TbInvestKsdAccountCheck {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheck.InvestId
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private Integer investId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheck.AskProcDt
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private String askProcDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheck.KsdReqSeq
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private Integer ksdReqSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheck.Stat
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private String stat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheck.ResultCode
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private String resultCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheck.RegDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private Date regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheck.ReqDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private Date reqDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbInvestKsdAccountCheck.ResDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	private Date resDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheck.InvestId
	 * @return  the value of TbInvestKsdAccountCheck.InvestId
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public Integer getInvestId() {
		return investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheck.InvestId
	 * @param investId  the value for TbInvestKsdAccountCheck.InvestId
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setInvestId(Integer investId) {
		this.investId = investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheck.AskProcDt
	 * @return  the value of TbInvestKsdAccountCheck.AskProcDt
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public String getAskProcDt() {
		return askProcDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheck.AskProcDt
	 * @param askProcDt  the value for TbInvestKsdAccountCheck.AskProcDt
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setAskProcDt(String askProcDt) {
		this.askProcDt = askProcDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheck.KsdReqSeq
	 * @return  the value of TbInvestKsdAccountCheck.KsdReqSeq
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public Integer getKsdReqSeq() {
		return ksdReqSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheck.KsdReqSeq
	 * @param ksdReqSeq  the value for TbInvestKsdAccountCheck.KsdReqSeq
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setKsdReqSeq(Integer ksdReqSeq) {
		this.ksdReqSeq = ksdReqSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheck.Stat
	 * @return  the value of TbInvestKsdAccountCheck.Stat
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheck.Stat
	 * @param stat  the value for TbInvestKsdAccountCheck.Stat
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setStat(String stat) {
		this.stat = stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheck.ResultCode
	 * @return  the value of TbInvestKsdAccountCheck.ResultCode
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public String getResultCode() {
		return resultCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheck.ResultCode
	 * @param resultCode  the value for TbInvestKsdAccountCheck.ResultCode
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheck.RegDate
	 * @return  the value of TbInvestKsdAccountCheck.RegDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheck.RegDate
	 * @param regDate  the value for TbInvestKsdAccountCheck.RegDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheck.ReqDate
	 * @return  the value of TbInvestKsdAccountCheck.ReqDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public Date getReqDate() {
		return reqDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheck.ReqDate
	 * @param reqDate  the value for TbInvestKsdAccountCheck.ReqDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setReqDate(Date reqDate) {
		this.reqDate = reqDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbInvestKsdAccountCheck.ResDate
	 * @return  the value of TbInvestKsdAccountCheck.ResDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public Date getResDate() {
		return resDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbInvestKsdAccountCheck.ResDate
	 * @param resDate  the value for TbInvestKsdAccountCheck.ResDate
	 * @mbggenerated  Thu Jan 28 17:28:27 KST 2016
	 */
	public void setResDate(Date resDate) {
		this.resDate = resDate;
	}
	
	public String getReplSeq() {
		return replSeq;
	}

	public void setReplSeq(String replSeq) {
		this.replSeq = replSeq;
	}

	private String replSeq;
}