package com.wadiz.client.kds.model;

import java.util.Date;

public class TbPersonalUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.UserId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.SSN1
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String ssn1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.SSN2
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String ssn2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.Location1
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String location1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.Location2
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String location2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.JobCode1
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String jobCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.JobCode2
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String jobCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.JobCode3
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String jobCode3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.ScrtCpCode
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String scrtCpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.ScrtAccountNo
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String scrtAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.RegDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.UpdateDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.Birth
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String Birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbPersonalUserInfo.Sex
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.UserId
     *
     * @return the value of TbPersonalUserInfo.UserId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.UserId
     *
     * @param userId the value for TbPersonalUserInfo.UserId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.SSN1
     *
     * @return the value of TbPersonalUserInfo.SSN1
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getSsn1() {
        return ssn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.SSN1
     *
     * @param ssn1 the value for TbPersonalUserInfo.SSN1
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setSsn1(String ssn1) {
        this.ssn1 = ssn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.SSN2
     *
     * @return the value of TbPersonalUserInfo.SSN2
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getSsn2() {
        return ssn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.SSN2
     *
     * @param ssn2 the value for TbPersonalUserInfo.SSN2
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setSsn2(String ssn2) {
        this.ssn2 = ssn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.Location1
     *
     * @return the value of TbPersonalUserInfo.Location1
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getLocation1() {
        return location1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.Location1
     *
     * @param location1 the value for TbPersonalUserInfo.Location1
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setLocation1(String location1) {
        this.location1 = location1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.Location2
     *
     * @return the value of TbPersonalUserInfo.Location2
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getLocation2() {
        return location2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.Location2
     *
     * @param location2 the value for TbPersonalUserInfo.Location2
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setLocation2(String location2) {
        this.location2 = location2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.JobCode1
     *
     * @return the value of TbPersonalUserInfo.JobCode1
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getJobCode1() {
        return jobCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.JobCode1
     *
     * @param jobCode1 the value for TbPersonalUserInfo.JobCode1
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setJobCode1(String jobCode1) {
        this.jobCode1 = jobCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.JobCode2
     *
     * @return the value of TbPersonalUserInfo.JobCode2
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getJobCode2() {
        return jobCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.JobCode2
     *
     * @param jobCode2 the value for TbPersonalUserInfo.JobCode2
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setJobCode2(String jobCode2) {
        this.jobCode2 = jobCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.JobCode3
     *
     * @return the value of TbPersonalUserInfo.JobCode3
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getJobCode3() {
        return jobCode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.JobCode3
     *
     * @param jobCode3 the value for TbPersonalUserInfo.JobCode3
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setJobCode3(String jobCode3) {
        this.jobCode3 = jobCode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.ScrtCpCode
     *
     * @return the value of TbPersonalUserInfo.ScrtCpCode
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getScrtCpCode() {
        return scrtCpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.ScrtCpCode
     *
     * @param scrtCpCode the value for TbPersonalUserInfo.ScrtCpCode
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setScrtCpCode(String scrtCpCode) {
        this.scrtCpCode = scrtCpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.ScrtAccountNo
     *
     * @return the value of TbPersonalUserInfo.ScrtAccountNo
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getScrtAccountNo() {
        return scrtAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.ScrtAccountNo
     *
     * @param scrtAccountNo the value for TbPersonalUserInfo.ScrtAccountNo
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setScrtAccountNo(String scrtAccountNo) {
        this.scrtAccountNo = scrtAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.RegDate
     *
     * @return the value of TbPersonalUserInfo.RegDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.RegDate
     *
     * @param regDate the value for TbPersonalUserInfo.RegDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.UpdateDate
     *
     * @return the value of TbPersonalUserInfo.UpdateDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.UpdateDate
     *
     * @param updateDate the value for TbPersonalUserInfo.UpdateDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.Birth
     *
     * @return the value of TbPersonalUserInfo.Birth
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getBirth() {
        return Birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.Birth
     *
     * @param Birth the value for TbPersonalUserInfo.Birth
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setBirth(String Birth) {
        this.Birth = Birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbPersonalUserInfo.Sex
     *
     * @return the value of TbPersonalUserInfo.Sex
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbPersonalUserInfo.Sex
     *
     * @param sex the value for TbPersonalUserInfo.Sex
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setSex(String sex) {
        this.sex = sex;
    }
}