package com.wadiz.client.kds.model;

public class TbUserAccntAuthKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuth.UserId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuth.AuthType
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String authType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuth.UserId
     *
     * @return the value of TbUserAccntAuth.UserId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuth.UserId
     *
     * @param userId the value for TbUserAccntAuth.UserId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuth.AuthType
     *
     * @return the value of TbUserAccntAuth.AuthType
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuth.AuthType
     *
     * @param authType the value for TbUserAccntAuth.AuthType
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setAuthType(String authType) {
        this.authType = authType;
    }
}