package com.wadiz.client.kds.model;

import java.util.Date;

public class TbUserAccntAuthHis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuthHis.HisNo
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private Integer hisNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuthHis.UserId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuthHis.AuthType
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String authType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuthHis.Status
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuthHis.ManagementId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String managementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuthHis.RegDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuthHis.AuthDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private Date authDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuthHis.HisNo
     *
     * @return the value of TbUserAccntAuthHis.HisNo
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public Integer getHisNo() {
        return hisNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuthHis.HisNo
     *
     * @param hisNo the value for TbUserAccntAuthHis.HisNo
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setHisNo(Integer hisNo) {
        this.hisNo = hisNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuthHis.UserId
     *
     * @return the value of TbUserAccntAuthHis.UserId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuthHis.UserId
     *
     * @param userId the value for TbUserAccntAuthHis.UserId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuthHis.AuthType
     *
     * @return the value of TbUserAccntAuthHis.AuthType
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuthHis.AuthType
     *
     * @param authType the value for TbUserAccntAuthHis.AuthType
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setAuthType(String authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuthHis.Status
     *
     * @return the value of TbUserAccntAuthHis.Status
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuthHis.Status
     *
     * @param status the value for TbUserAccntAuthHis.Status
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuthHis.ManagementId
     *
     * @return the value of TbUserAccntAuthHis.ManagementId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getManagementId() {
        return managementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuthHis.ManagementId
     *
     * @param managementId the value for TbUserAccntAuthHis.ManagementId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setManagementId(String managementId) {
        this.managementId = managementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuthHis.RegDate
     *
     * @return the value of TbUserAccntAuthHis.RegDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuthHis.RegDate
     *
     * @param regDate the value for TbUserAccntAuthHis.RegDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuthHis.AuthDate
     *
     * @return the value of TbUserAccntAuthHis.AuthDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public Date getAuthDate() {
        return authDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuthHis.AuthDate
     *
     * @param authDate the value for TbUserAccntAuthHis.AuthDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setAuthDate(Date authDate) {
        this.authDate = authDate;
    }
}