package com.wadiz.client.kds.model;

import java.util.Date;

public class TbUserAccntAuth extends TbUserAccntAuthKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuth.Status
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuth.ManagementId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private String managementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuth.RegDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbUserAccntAuth.AuthDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    private Date authDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuth.Status
     *
     * @return the value of TbUserAccntAuth.Status
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuth.Status
     *
     * @param status the value for TbUserAccntAuth.Status
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuth.ManagementId
     *
     * @return the value of TbUserAccntAuth.ManagementId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public String getManagementId() {
        return managementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuth.ManagementId
     *
     * @param managementId the value for TbUserAccntAuth.ManagementId
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setManagementId(String managementId) {
        this.managementId = managementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuth.RegDate
     *
     * @return the value of TbUserAccntAuth.RegDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuth.RegDate
     *
     * @param regDate the value for TbUserAccntAuth.RegDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbUserAccntAuth.AuthDate
     *
     * @return the value of TbUserAccntAuth.AuthDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public Date getAuthDate() {
        return authDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbUserAccntAuth.AuthDate
     *
     * @param authDate the value for TbUserAccntAuth.AuthDate
     *
     * @mbggenerated Sun Jan 24 23:46:46 KST 2016
     */
    public void setAuthDate(Date authDate) {
        this.authDate = authDate;
    }
}